name: Deploy Project
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: run npm ci
              run: npm ci
            - name: perform unit test
              run: npm test
    deploy:
      needs: build   #dependency build with test.Build job will initiate if test job gets successfully
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: build project
          run: npm run build
        - name: Deploy
          run: echo "Deploying....."

