name: Test Project
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: run npm ci
              run: nmp ci
            - name: perform unit test
              run: npm test